#입력
x = int(input ('숫자를 입력하시오'))
y = int(input ('숫자를 입력하시오'))
print(type(x))
print(x,'+', y, end='=')
print(x+y)
print(str(x) +'+'+ str(y) + '=')
print(x+y)
print(f'{x}+{y}={x+y}')
print(f'{x}-{y}={x-y}')
print(f'{x}X{y}={x*y}')
print(f'{x}/{y}={x/y:.2}')

print(f'{x}//{y}={x//y}')
print(f'{x}%{y}={x%y}')
print(f'{x}/{y}={x/y}')
print('='*50)
print(f'{x}^{y}={x**y}')
